### ISSUE TITLE
Partials don't resolve correctly on Windows

### ISSUE THREAD

**Issue by techiedarren** [SungardAS/condensation#12]
When resolving a particle (partial, helper etc) on windows the path resolution fails because of hard coded path separators.

particle-loader.js
particle.modulePath = opts.parentFile.path.slice(0,opts.parentFile.path.lastIndexOf('/particles/'));

On windows, the path is \particles\ so this fails. It should use path.sep instead.

**Comment by kmcgrath** [comment]
Someone brought this to my attention last week. I pushed an attempt at a fix in version 0.2.4.  I actually just pushed this to npm a few minutes ago.

Can you try with the new version and let me know if that works?  I don't have a Windows VM handy to test at this time.
