### ISSUE TITLE
Particles in scoped packages not found by particle loader

### ISSUE THREAD

**Issue by ModeEngage** [SungardAS/condensation#25]
Attempting to access resources from a dependency with a scoped package name always results in the particle not being found at build time.

```
{{resource "m:@package_scope/common" "sns\email_topic"
    name=(fnJoin "-" (cValue stackName) "pipeline-topic")
    email="redacted@redacted.com"
    logicalId="SnsTopic"
}}
```

https://docs.npmjs.com/misc/scope

**Comment by kmcgrath** [comment]
I will need to create a project with `npm scope` dependencies to test this out.  In the meantime could you try to load the module with the full syntax described [here](https://github.com/SungardAS/condensation/blob/master/docs/particle-helpers.md#particlehelpers)

changing the **m** to **module**
```
{{resource "module:@package_scope/common" "sns\email_topic"
    name=(fnJoin "-" (cValue stackName) "pipeline-topic")
    email="redacted@redacted.com"
    logicalId="SnsTopic"
}}
```

**Comment by ModeEngage** [comment]
```
{{resource "module:@package_scope\particles-fully-qualified-common" "sns\email_topic"
    name=(fnJoin "-" (cValue stackName) "pipeline-topic")
    email="redacted@redacted.com"
    logicalId="SnsTopic"
}}
```
This seems to build -- so perhaps this isn't a bug; didn't think to add the full 'module:'

**Comment by kmcgrath** [comment]
Glad that worked for you.  Please let us know if you do find any edge cases with `npm scope`, it is not something we are currently using.

**Comment by ModeEngage** [comment]
Unfortunately, now that I've moved the condensation scripts from my windows dev box to an ubuntu build box, particle loads from scoped packages are back to failing -- any idea why this would manifest in linux and not windows?

```
$ npm -v
3.10.10
$ node -v
v6.10.2
```

**Comment by kmcgrath** [comment]
Don't know why that would be. We mostly (almost exclusively) use Mac/Linux for dev and test. After you closed the issue initially I did not go back and try a scoped package.  I can look into that.

The issue is only around scoped packages, correct?

**Comment by ModeEngage** [comment]
Correct. I am importing particles from a common package, and receiving the following error:

```
Layout Parse Error in file /jenkins-slave/workspace/Infrastructure/redacted/particles/cftemplates/bootstrap.dev.template.hbs: resource iam\auth0-saml-role refrenced in /jenkins-slave/workspace/Infrastructure/redacted/particles/cftemplates/bootstrap.dev.template.hbs could not be found: particle load error
```

**Comment by kmcgrath** [comment]
If I had to guess it is the backslash here: `iam\auth0-saml-role`

I'm guessing if that was `iam/auth0-saml-role` it would work.  We try to use the native `path` module anywhere we can so that paths "just work" between windows and linux, but there may be a bug.

Does switching to a forward slash on windows cause an error?

**Comment by ModeEngage** [comment]
That's totally the problem. Shoulda noticed that -- forward slashes work fine on windows. Thanks.
